---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-22/ee-supported-rhel8' 

dependencies:
  galaxy: requirements.yml
  python: requirements.txt

additional_build_steps:
  prepend: |
    RUN microdnf install libcurl-devel gcc python39-devel openssl-devel gpgme-devel python3-dmidecode python3-rpm python3-syspurpose
    RUN pip3 install pycurl
    RUN microdnf install libxml2-devel
  append:
    - RUN echo JUST FINISHING UP... HANG TIGHT 
    - RUN ls -la /runner
    - RUN ls -la /output


#<!--
#
# Reference: 
# - https://docs.ansible.com/automation-controller/latest/html/userguide/ee_reference.html 
#
#-->


